export let products = [
  {
    title: "Camiseta Argentina",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802036/argentina_rii8mx.png",
    detail:
      "La camiseta titular de la Selección Argentina combina el albiceleste con el color dorado, y la alternativa presenta un tono azulado.",
  },
  {
    title: "Camiseta Arsenal",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802036/arsenal_ladfjx.png",
    detail: "",
  },
  {
    title: "Camiseta Barcelona",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802035/barca_vbycnm.png",
    detail: "",
  },
  {
    title: "Camiseta Boca",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802035/boca_cvo5st.png",
    detail: "",
  },
  {
    title: "Camiseta Brasil",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802036/brasil_kp6vht.png",
    detail: "",
  },
  {
    title: "Camiseta M City",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1719166170/city_yqf5ar.png",
    detail: "",
  },
  {
    title: "Camiseta Colombia",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/colombia_elkojb.png",
    detail: "",
  },
  {
    title: "Camiseta Croacia",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/croacia_kosukm.png",
    detail: "",
  },
  {
    title: "Camiseta España",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/espana_njakuz.png",
    detail: "",
  },
  {
    title: "Camiseta Everton",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/everton_hljmoh.png",
    detail: "",
  },
  {
    title: "Camiseta Francia",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/francia_mkynqi.png",
    detail: "",
  },
  {
    title: "Camiseta Galatasaray",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802037/galatasaray_gf7mxf.png",
    detail: "",
  },
  {
    title: "Camiseta Holanda",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802038/holanda_ig8ev3.png",
    detail: "",
  },
  {
    title: "Camiseta Inglaterra",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802054/inglaterra_v3k0s6.png",
    detail: "",
  },
  {
    title: "Camiseta Italia",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802070/italia_emgz5e.png",
    detail: "",
  },
  {
    title: "Camiseta Juventus",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802086/juventus_hl6mag.png",
    detail: "",
  },
  {
    title: "Camiseta Nacional",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802314/nacional_emq3el.png",
    detail: "",
  },
  {
    title: "Camiseta Noruega",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802314/noruega_pzzk4m.png",
    detail: "",
  },
  {
    title: "Camiseta Penarol",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802314/penarol_rj9y3z.png",
    detail: "",
  },
  {
    title: "Camiseta Portugal",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802314/portugal_zbvujv.png",
    detail: "",
  },
  {
    title: "Camiseta PSG",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802314/psg_v1wl8g.png",
    detail: "",
  },
  {
    title: "Camiseta Pumas",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802315/pumas_v3zxgs.png",
    detail: "",
  },
  {
    title: "Camiseta River",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802315/river_rwvzyj.png",
    detail: "",
  },
  {
    title: "Camiseta Romas",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802315/roma_oqadui.png",
    detail: "",
  },
  {
    title: "Camiseta Uruguay",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802315/uruguay_zryxv6.png",
    detail: "",
  },
  {
    title: "Camiseta USA",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802316/usa_xcak03.png",
    detail: "",
  },
  {
    title: "Camiseta Zenit",
    price: 49.99,
    category: "Camisetas",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802316/zenit_rd3son.png",
    detail: "",
  },

  {
    title: "Short M. United",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810238/shorts-united_zhsgrk.png",
    detail: "",
  },
  {
    title: "Short Roma",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810236/shorts-roma_t1mkjc.png",
    detail: "",
  },
  {
    title: "Short R. Madrid",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810232/shorts-real_wandey.png",
    detail: "",
  },
  {
    title: "Short Puma Negro",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810231/shorts-puma1_l7yaeo.png",
    detail: "",
  },
  {
    title: "Short Puma Gris",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810228/shorts-puma_r7bnty.png",
    detail: "",
  },
  {
    title: "Short Milan",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810226/shorts-milan_ksikfz.png",
    detail: "",
  },
  {
    title: "Short Dormund",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810222/shorts-dormund_xw3c7m.png",
    detail: "",
  },
  {
    title: "Short M. City",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810220/shorts-city_urvyzy.png",
    detail: "",
  },
  {
    title: "Short Chelsea",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810219/shorts-chelsea_u6vfpn.png",
    detail: "",
  },
  {
    title: "Short Barcelona",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810214/shorts-barca_ocyw2a.png",
    detail: "",
  },
  {
    title: "Short At. Madrid",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810210/shorts-atletico_qeivsz.png",
    detail: "",
  },
  {
    title: "Short U. Armor Negro",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810209/short-under3_znggv8.png",
    detail: "",
  },
  {
    title: "Short U. Armor Verde",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810206/short-under2_pyvfc1.png",
    detail: "",
  },
  {
    title: "Short U. Armor Gris",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810204/short-under1_ecjtdp.png",
    detail: "",
  },
  {
    title: "Short Nike Verde",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810201/short-nike5_x8lxpa.png",
    detail: "",
  },
  {
    title: "Short Totenham",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810200/short-nike4_wwuytd.png",
    detail: "",
  },
  {
    title: "Short Nike Negro",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810197/short-nike3_taytdl.png",
    detail: "",
  },
  {
    title: "Short Nike Pipa",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810196/short-nike2_vid5x9.png",
    detail: "",
  },
  {
    title: "Short Nike Retro",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810191/short-nike1_bjpmlh.png",
    detail: "",
  },
  {
    title: "Short Adidas",
    price: 28.99,
    category: "Shorts",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810190/short-adidas1_lzd9ss.png",
    detail: "",
  },

  {
    title: "Medias Nike Roja",
    price: 28.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802880/med-nike1_xdpdrt.png",
    detail: "",
  },
  {
    title: "Medias Adidas Negra",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802880/med-adidas8_or7ewn.png",
    detail: "",
  },
  {
    title: "Medias Adidas Verde",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802544/med-adidas3_sv4j1t.png",
    detail: "",
  },
  {
    title: "Medias Reebok",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802881/med-reebok3_wqzzak.png",
    detail: "",
  },
  {
    title: "Medias Goal",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802880/med-goal1_jbg49e.png",
    detail: "",
  },
  {
    title: "Medias Umbro",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802881/med-umbro1_xq4uec.png",
    detail: "",
  },
  {
    title: "Medias Asics",
    price: 8.99,
    category: "Medias",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802880/med-asics1_a9nf37.png",
    detail: "",
  },

  {
    title: "Zapato Umbro",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810132/umbro-pasto1_vapxxl.png",
    detail: "",
  },
  {
    title: "Zapato Puma",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810131/puma-pasto3_qeg8ut.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810126/nike-pasto5_q4yasb.png",
    detail: "",
  },
  {
    title: "Zapato Puma Negro",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810126/puma-pasto2_owtstv.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810117/nike-pasto3_d5nsar.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810116/nike-pasto2_pij9ur.png",
    detail: "",
  },
  {
    title: "Zapato Loto",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810110/lotto-pasto2_onbmgn.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718808688/adid-pasto9_wry9r5.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718808637/adid-pasto4_a9marr.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718808635/adid-pasto3_xjbxyz.png",
    detail: "",
  },
  {
    title: "Zapato Umbro",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810177/umbro-salon3_qft5os.png",
    detail: "",
  },
  {
    title: "Zapato Umbro",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810172/umbro-salon1_rhaaxu.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810167/nike-salon3_bvyc37.png",
    detail: "",
  },
  {
    title: "Zapato Loto",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810161/lotto-salon3_ea4sat.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810154/adid-salon8_q7rwzo.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810147/adid-salon5_l36hjv.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810136/adid-salon1_o6zc4o.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810162/nike-salon1_arqkcp.png",
    detail: "",
  },
  {
    title: "Zapato Under Armor",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810295/undercorrer2_idhne4.png",
    detail: "",
  },
  {
    title: "Zapato Under Armor",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810298/undercorrer3_b0yqjt.png",
    detail: "",
  },

  {
    title: "Zapato Puma",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810289/pumacorrer3_b2spnx.png",
    detail: "",
  },
  {
    title: "Zapato Puma",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810286/pumacorrer2_mrbmpc.png",
    detail: "",
  },
  {
    title: "Zapato Nike",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810282/nikecorrer3_liywbn.png",
    detail: "",
  },
  {
    title: "Zapato New Balance",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810276/newbalancorrer4_qq6az9.png",
    detail: "",
  },
  {
    title: "Zapato Fila",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810267/filacorrer1_odbxms.png",
    detail: "",
  },
  {
    title: "Zapato Asics",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810262/asicscorrer2_rv0mar.png",
    detail: "",
  },
  {
    title: "Zapato Asics",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810264/asicscorrer3_zqbspw.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810258/adidascorrer4_ttyelg.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810254/adidascorrer3_nnpks4.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810250/adidascorrer1_peu0re.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810247/adidasbasket4_etuved.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810242/adidasbasket2_low99j.png",
    detail: "",
  },
  {
    title: "Zapato Adidas",
    price: 89.99,
    category: "Zapatos",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718810240/adidasbasket1_gulg1k.png",
    detail: "",
  },
  {
    title: "Pelota Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718808085/pelot-nike-fut9_kmy6zv.png",
    detail: "",
  },
  {
    title: "Pelota Puma",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718808027/pelot-puma-fut4_f3cbjr.png",
    detail: "",
  },
  {
    title: "Pelota Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803364/pelot-nike-fut6_heaexa.png",
    detail: "",
  },
  {
    title: "Pelota Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803039/pelot-adidas-fut2_rwqdkr.png",
    detail: "",
  },
  {
    title: "Pelota Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803039/pelot-adidas-basket_xp75g7.png",
    detail: "",
  },
  {
    title: "Riñonera Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803038/rinonera-adidas_khmyhf.png",
    detail: "",
  },
  {
    title: "Nuñequera Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803037/munequera-nike3_amponz.png",
    detail: "",
  },

  {
    title: "Mochila Puma",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803037/mochila-puma_surhh7.png",
    detail: "",
  },
  {
    title: "Mochila Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/mochila-nike_ylc6zm.png",
    detail: "",
  },
  {
    title: "Muñequera Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803037/munequera-nike1_vq7byj.png",
    detail: "",
  },
  {
    title: "Gorro Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/gorro-nike_ez1esa.png",
    detail: "",
  },
  {
    title: "Botella Puma",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/botella-puma1_xb2nfv.png",
    detail: "",
  },
  {
    title: "Protector Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803037/protector-bucal-nike1_oudglx.png",
    detail: "",
  },
  {
    title: "Gorro U. Armor",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/gorra-under_q0w1t1.png",
    detail: "",
  },
  {
    title: "Gorro Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/gorro-adidas_jdpwl9.png",
    detail: "",
  },
  {
    title: "Canillera Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803036/canilleras-nike_lgtcci.png",
    detail: "",
  },
  {
    title: "Canillera Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803035/canilleras-adidas_snughh.png",
    detail: "",
  },
  {
    title: "Visera Fila",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803039/visera-fila2_bxeduf.png",
    detail: "",
  },
  {
    title: "Botella Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802923/botella-adidas-1_zdfvpq.png",
    detail: "",
  },
  {
    title: "Visera U. Armor",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718803039/visera-under1_appmca.png",
    detail: "",
  },
  {
    title: "Bolso Puma",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802882/bolso-puma_k0txeg.png",
    detail: "",
  },
  {
    title: "Bolso Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802882/bolso-nike_e3a3bp.png",
    detail: "",
  },
  {
    title: "Mochila Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802881/bandolera-nike_syf8br.png",
    detail: "",
  },
  {
    title: "Guantes Reusch",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802486/guantes-reusch2_hicber.png",
    detail: "",
  },
  {
    title: " Guantes Puma",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802486/guantes-puma1_xdqccw.png",
    detail: "",
  },
  {
    title: "Guantes Nike",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802485/guantes-nike7_pydnhk.png",
    detail: "",
  },
  {
    title: "Guantes Rinat",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802486/guantes-rinat1_upijbm.png",
    detail: "",
  },

  {
    title: "Guantes Adidas",
    price: 89.99,
    category: "Otros",
    stock: 10,
    img: "https://res.cloudinary.com/dqh95knoj/image/upload/v1718802483/guantes-adidas2_th5z7z.png",
    detail: "",
  },
];
